// Generated by CoffeeScript 1.9.3
(function() {
  $('document').ready(function() {
    $('body')[0].addEventListener('drop', (function(event) {
      return event.preventDefault();
    }), false);
    window.Peanutty = Peanutty;
    return window.b2d = Peanutty.b2d;
  });

}).call(this);
